### ISSUE TITLE
[TODO] 抽离Config，支持使用npm安装

### ISSUE THREAD

**Issue by mintfog** [f-dong/hexo-theme-minimalism#12]

**Comment by f-dong** [comment]
Hexo 已提供 https://hexo.io/zh-cn/docs/configuration.html#%E4%BD%BF%E7%94%A8%E4%BB%A3%E6%9B%BF%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
