### ISSUE TITLE
[BUG] 导航栏中间位置有一个隐形链接

### ISSUE THREAD

**Issue by zyrate** [f-dong/hexo-theme-minimalism#16]
作者你好，很喜欢这个主题，但是好像发现一个问题，就是在导航栏的中部有一个地方鼠标放上去会变成手型，点击会跳转到分类页面，不知道是什么原因：
![image](https://user-images.githubusercontent.com/34681639/230376153-d3c4f2c9-2b08-4b04-a842-96116dafa559.png)

跳转到分类页面：

![image](https://user-images.githubusercontent.com/34681639/230376321-28dcdedb-74a9-4d9b-87a8-8ca77d8b3f50.png)

不知道是有意为之还是BUG，谢谢！

**Comment by f-dong** [comment]
是BUG，近两天会修复，你可以关注这条issue，修复后我会在这里回复！




---原始邮件---
发件人: "Yunrui ***@***.***&gt;
发送时间: 2023年4月6日(周四) 晚上8:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [f-dong/hexo-theme-minimalism] [BUG] 导航栏中间位置有一个隐形链接 (Issue #16)




 
作者你好，很喜欢这个主题，但是好像发现一个问题，就是在导航栏的中部有一个地方鼠标放上去会变成手型，点击会跳转到分类页面，不知道是什么原因：
 
 
跳转到分类页面：
 

 
不知道是有意为之还是BUG，谢谢！

**Comment by zyrate** [comment]
好的，谢谢！

**Comment by f-dong** [comment]
问题已解决，你可以覆盖主题文件进行更新（注意备份配置文件）
