### ISSUE TITLE
文章摘要沒有自動顯示

### ISSUE THREAD

**Issue by rhythm16** [f-dong/hexo-theme-minimalism#2]
`README.md` 最下面有寫：
> summary: 这是你自定义的文章摘要内容，如果这个属性有值，文章卡片摘要就显示这段文字，否则程序会自动截取文章的部分内容作为摘要

但我測試如果沒有設定summary，就沒有任何的文章摘要，請我有地方設定錯嗎？Thanks!

**Comment by f-dong** [comment]
根據你的描述我成功復現了這個問題，看來是不符合預期的。我已將最新的修訂推送至了 master，你可以更新以應用修復，感謝你的使用
