### ISSUE TITLE
[BUG] 图片无法正常加载

### ISSUE THREAD

**Issue by Apocalypsor** [f-dong/hexo-theme-minimalism#20]
**提交前检查单**
- [x] 已尝试执行 `hexo clean`，问题仍然存在

**Bug 描述**
最新的1.3.3版本，图片无法正常加载

**复现方法**
复现该 Bug 的步骤：

文章中插入图片
```
![test](/image/test.png)
```

**预期结果**
该功能本来应该是怎么样的

图片正常载入

**截图**
如果可以，请添加截图以帮助解释您的问题。

生成的html代码变成了
```
<a class="simple-lightbox" href="/image/test.png" one-link-mark="yes"><img src="/images/loading.svg" data-src="/image/test.png" alt="test" lazyload=""></a>
```

一直停留在加载界面
<img width="441" alt="image" src="https://user-images.githubusercontent.com/37431235/231342899-89f7ce9d-7cd3-4d7d-b016-18ba0af0a0c2.png">

**Comment by Apocalypsor** [comment]
经过测试，是插件`hexo-blog-encrypt`的问题，如果使用该插件并设置密码，会导致边框栏和图片都无法载入

**Comment by f-dong** [comment]
是的，如有需要你可以创建新的 issues 并引入此问题（选择功能建议），我会视情况在后续版本中兼容该插件。

如果只是想解决图片无法加载的问题，可在主题配置文件中，将 `image.lazyload_enable` 配置值设为 `false` 即可
