### ISSUE TITLE
[功能建议] 兼容插件 hexo-blog-encrypt

### ISSUE THREAD

**Issue by Apocalypsor** [f-dong/hexo-theme-minimalism#21]
**功能概述**
兼容插件 `hexo-blog-encrypt`
项目地址：https://github.com/D0n9X1n/hexo-blog-encrypt
目前使用该插件加密文章会导致以下几个问题
+ 开启懒加载后图片无法载入
+ 边栏无法显示

**Comment by f-dong** [comment]
我已向 `hexo-blog-encrypt` 提交了 PR，但该扩展包作者未将更改成功推送至 NPM，因此目前无法做到完全兼容，可等待该插件下次更新后即可天然兼容

---

临时解决办法，在需要加密的文章内容底部添加以下代码：

```html
<script>themeBoot();</script>
```


> 注：需确保本主题版本大于等于 V1.3.6

**Comment by Apocalypsor** [comment]
好的，感谢大佬
