### ISSUE TITLE
[功能建议] opengraph 的支持

### ISSUE THREAD

**Issue by a-wing** [f-dong/hexo-theme-minimalism#25]
**功能概述**
对于一些社交平台提供预览的功能 https://ogp.me/

**图片描述**

twitter 的卡片预览效果：

<img width="592" alt="Screenshot 2023-05-03 at 16 42 58" src="https://user-images.githubusercontent.com/18189138/235870009-f8cef696-00af-4859-84d2-96f5197f452e.png">

Telegram 的卡片预览效果：

<img width="375" alt="Screenshot 2023-05-03 at 16 43 37" src="https://user-images.githubusercontent.com/18189138/235870509-3be742b7-8356-4802-8c5d-17395fbddabc.png">

**Comment by f-dong** [comment]
V1.3.6版本以支持
