### ISSUE TITLE
[功能建议] 此功能概述

### ISSUE THREAD

**Issue by Jamarcus-H** [f-dong/hexo-theme-minimalism#27]
**功能概述**
请提供这个功能应该是什么样的

**图片描述**
可选，可以用你的毕加索画作

**Comment by Jamarcus-H** [comment]
**功能概述**
我希望评论系统能够支持Gitee，毕竟Github在国内的访问情况实在是不友好。

**图片描述**
![image](https://github.com/f-dong/hexo-theme-minimalism/assets/134684656/14e3a636-f389-4a1a-bcce-cd25fb34db47)

**Comment by f-dong** [comment]
Github 访问速度确实堪忧，但据我所知，Gitee 并未向个人用户开放 OAuth Api，利用 Gitee Issues 作为评论系统是行不通的。

不过，在最新的 1.3.6 版本中，已引入了 [twikoo](https://twikoo.js.org/) 评论系统，国内速度尚可，且无需评论用户登录。该评论系统需要私有部署，可以参考 [Twikoo 官方文档](https://twikoo.js.org/quick-start.html) 查看配置教程，建议使用 `Vercel 部署` ，如果配置有障碍，可将你的信息发送至我的个人邮箱 fdong26@gmail.com，在我闲暇时会帮你进行配置
