### ISSUE TITLE
[BUG]文章置顶不起作用

### ISSUE THREAD

**Issue by Theo-messi** [f-dong/hexo-theme-minimalism#39]
**提交前检查单**
- [x] 已尝试执行 `hexo clean`，问题仍然存在

**Bug 描述**
清晰地描述，请提供
```md
---
top: true
toc: false
sticky: 999
---
```
按照如下设置,置顶文章不起任何作用

**Comment by f-dong** [comment]
这里是 HEXO 本身自带的一个功能，不止为何确实不在起作用了，我已经提交 issues，你可以关注状态，如果官方无法提出有效解决方案，我会再想办法从主题内调整这个功能
https://github.com/hexojs/hexo-generator-index/issues/101

**Comment by f-dong** [comment]
我的问题，之前在一个版本中，对首页文章进行了重新排序，导致 sticky 失效，我已修改此问题，更新主题版本至 1.3.11 即可解决
