### ISSUE TITLE
markdown空格转义字符解析不出来

### ISSUE THREAD

**Issue by yangqun-git** [f-dong/hexo-theme-minimalism#4]
`&emsp;` 这个转义字符代表一个全角的空格，在本地markdown编辑器可以正常显示空格。通过hexo部署后显示字符`&emsp;`而不是空格。

**Comment by f-dong** [comment]
这似乎是 hexo 的问题，参考 [https://github.com/hexojs/hexo/issues/4946](https://github.com/hexojs/hexo/issues/4946)

将 package.json 中，`hexo-renderer-marked` 降级为 4.x 即可
