### ISSUE TITLE
[功能建议] 页面宽度在 1230 左右会出现横向滚动条

### ISSUE THREAD

**Issue by lai9fox** [f-dong/hexo-theme-minimalism#42]
出现横向滚动条时，需要左右滚动才能看到 toc 的全部内容

能否改变内容的宽度，不出现横向滚动条呢

**截图**
如果可以，请添加截图以帮助解释您的问题。

![截图](https://github.com/user-attachments/assets/0ea4c5de-e36a-448e-8154-570f253a3dd8)

**电脑（请填写以下信息）：**
 - 操作系统：macOS
 - 浏览器 Chrome
 - 版本 126

**Comment by f-dong** [comment]
这个我已经修改（大于1400才显示 toc），计划在近两天随另一个问题一起发布新的版本，版本号或许是 1.3.12
