### ISSUE TITLE
[功能建议] 新增联系方式-联系邮箱

### ISSUE THREAD

**Issue by K4N114** [f-dong/hexo-theme-minimalism#46]
**功能概述**
将联系邮箱作为一个图标添加到联系方式一栏中

**图片描述**
![image](https://github.com/user-attachments/assets/7b126bbd-4a28-4282-8380-16b58ded8b2e)

**Comment by f-dong** [comment]
已处理，更新主题版本至 1.4.2

**Comment by li199-code** [comment]
下载试了，有bug。点击邮件图标跳转的链接应该是：`mailto:xxx@xx.com`
