### ISSUE TITLE
[BUG]升级到1.4.2后图标显示不正常

### ISSUE THREAD

**Issue by sevndata** [f-dong/hexo-theme-minimalism#48]
**提交前检查单**
- [x] 已尝试执行 `hexo clean`，问题仍然存在

**Bug 描述**
升级到1.4.2后图标显示不正常，浏览器报错	/style/iconfont.woff2 404未找到，fonts.styl文件回退版本或者iconfont拷贝到/style/目录下显示正常

**Comment by f-dong** [comment]
好的，是我疏忽了，已重新修改
